require('./controller/subsistema.controller')
require('./controller/bote.controller')
require('./controller/especie.controller')
require('./controller/carnada.controller')
require('./controller/unidad.controller')
require('./controller/zona.controller')
require('./controller/sector.controller')
require('./controller/viaje.controller')
require('./controller/carnada_registro.controller')
require('./controller/trampa_historico')

